Repository srijanone/vega, pull requests merged in 2020-07, with the labels that each got.

#76 Add Hook: Prevent Committing AWS Credentials
  Makefile
  cmd/init.go
  hooks/generic/pre-commit/check-aws-keys.sh
  pkg/common/common_service.go
  pkg/core/git_hooks.go
  pkg/core/home.go
  pkg/git/git.go
  scripts/setup_hooks.sh
Labels: feature

#90 Rename _screenshot to .screenshot
  .screenshots/vega_create.png
  .screenshots/vega_down.png
  .screenshots/vega_init.png
  .screenshots/vega_starterkit_list.png
  .screenshots/vega_up.png
  .screenshots/vega_usage.png
  README.md
Labels: cosmetic-changes

#89 Added vega hooks install command for existing projects
  README.md
  cmd/create.go
  cmd/down.go
  cmd/hooks.go
  cmd/hooks_install.go
  cmd/init.go
  cmd/root.go
  cmd/up.go
  hooks/generic/pre-commit/check-aws-keys.sh
  pkg/common/common_service.go
  pkg/core/git_hooks.go
  pkg/core/vega.go
  pkg/git/git.go
  pkg/tilt/tilt.go
Labels: enhancement

#106 Functionality to Install Vega Starterkits to Existing Projects
  README.md
  cmd/install.go
  cmd/root.go
  pkg/core/starterkit.go
Labels: enhancement

#105 Update shell escape code to make it work on all platforms
  scripts/install.sh
Labels: bug

#129 Show select list for crete command
  cmd/create.go
  cmd/starterkit_list.go
Labels: enhancement
